### PR TITLE
Add Phoenix, AZ template

### PR DESCRIPTION
**Pull request by cstrouse**

### CODE REVIEW

**Comment by teddywilson** [comment]
so sorry, i had to do a force push to gh-pages :^(  would you mind merging that branch back in so I can review?

**Comment by alloypedal** [comment]
[Here are the Phoenix emails](https://twitter.com/PhxProtestLIVE/status/1268787049156374528?s=20)

**Comment by mnazaussie** [comment]
Thank you.

**Comment by minicreative** [comment]
Closing because stale. Thank you!

**Pull request closed without merging**
