### PR TITLE
Add social card image and favicon

### PR DESCRIPTION
**Pull request by skullface**
This PR builds off of #351 to add social sharing visuals and additional metadata protocols ~

### Favicon
| OS Light mode | OS Dark mode | Colorblind users |
| --- | --- | --- |
| Screen Shot 2020-06-05 at 11 16 42 PM | Screen Shot 2020-06-05 at 11 16 14 PM | Screen Shot 2020-06-05 at 11 16 57 PM |

### Social share preview
Screen Shot 2020-06-05 at 11 17 42 PM

### CODE REVIEW

**Comment by teddywilson** [comment]
This is so sick

**Comment by nickschollVEVO** [comment]
Well done, @skullface! 

BTW when this gets deployed, we need to visit https://developers.facebook.com/tools/debug and re-scrape.

**Comment by teddywilson** [comment]
Oh, good call! I was honestly not aware of this. The change is already live! I'll add now.

**Comment by teddywilson** [comment]
```
caution-solidWarnings That Should Be Fixed
Missing Properties
The following required properties are missing: og:url, og:type, fb:app_id
```

**Comment by skullface** [comment]
Awesome, I’ll address those in a new PR~

**Pull request merged**
