### PR TITLE
Add Seattle, WA template

### PR DESCRIPTION
**Pull request by dorazhao99**

### CODE REVIEW

**Comment by teddywilson** [comment]
Hey, thanks for the contribution!

It looks like this one is missing some specific information about Seattle. Can we provide some more detailed information?

**Comment by dorazhao99** [comment]
Yes, I added some specifics about the Seattle budget. Let me know if I should add anything else!

**Comment by teddywilson** [comment]
so sorry, i had to do a force push to gh-pages :^(  would you mind merging that branch back in so I can review?

**Comment by lleadbet** [comment]
Relates to issue #188

**Pull request closed without merging**
